### ISSUE TITLE
Check command - make github-fetcher smarter

### ISSUE THREAD

**Issue by alexalikiotis** [nodeshift/oratrix#30]
@helio-frota I'm opening this issue as a recommendation to make the GitHub fetcher smarter like:

- What happens if the organization has more than 50 repos ??
- What if a repo is deprecated ?? (we should probably drop it)
- etc.

**Comment by helio-frota** [comment]
Thanks for open the issue.

> What happens if the organization has more than 50 repos ??

So for now that is a "demo" code and I believe github has restrictions of access related to the API I remember that when using sometimes the scripts https://github.com/nodeshift-starters/scripts
And probably we need to work with github api token to avoid that restrictions or something.

> What if a repo is deprecated ?? (we should probably drop it)

Yeah that can be hard because the deprecation can be just a text in README... but we can probably try to investigate if the project is "archived" `"archived": true,`

**Comment by helio-frota** [comment]
Let's break this issue in two for now so that we can work on the "archived" part , wdyt ?

**Comment by alexalikiotis** [comment]
Some issues mentioned in this thread were split into #32 #31

**Comment by helio-frota** [comment]
Thanks for open the issues, I think we can close this and keep the others opened :+1:  closing...
